// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:46:15 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "alac.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

