// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 22 May 2016 01:51:33 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "alac.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

