// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:46:15 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package alac provides Go bindings for ALAC decoder (C version by David Hammerton).
*/
package alac
