// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 23 Jan 2016 21:34:01 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package alac provides Go bindings for ALAC decoder (C version by David Hammerton).
*/
package alac
