// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jan 2016 05:31:55 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package alac

/*
#include "alac.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// File as declared in alac/alac.h:6
type File struct {
	InputBuffer               []byte
	InputBufferBitaccumulator int
	Samplesize                int
	Numchannels               int
	Bytespersample            int
	PredicterrorBufferA       []int
	PredicterrorBufferB       []int
	OutputsamplesBufferA      []int
	OutputsamplesBufferB      []int
	UncompressedBytesBufferA  []int
	UncompressedBytesBufferB  []int
	SetinfoMaxSamplesPerFrame uint
	Setinfo7a                 byte
	SetinfoSampleSize         byte
	SetinfoRiceHistorymult    byte
	SetinfoRiceInitialhistory byte
	SetinfoRiceKmodifier      byte
	Setinfo7f                 byte
	Setinfo80                 uint16
	Setinfo82                 uint
	Setinfo86                 uint
	Setinfo8aRate             uint
	ref9e6cbf0e               *C.alac_file
	allocs9e6cbf0e            interface{}
}
